# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-30 22:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('access_token', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('ts_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'userToken',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('salt', models.CharField(max_length=16)),
                ('pro_pic', models.CharField(default=b'NA', max_length=200)),
                ('google_id', models.CharField(default=b'NA', max_length=200)),
                ('google_link', models.CharField(default=b'NA', max_length=200)),
                ('facebook_id', models.CharField(default=b'NA', max_length=200)),
                ('facebook_link', models.CharField(default=b'NA', max_length=200)),
                ('user_id', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_verified', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'userDB',
            },
        ),
        migrations.AddField(
            model_name='token',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.User'),
        ),
    ]
