# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-12 23:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmarks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('des', models.CharField(max_length=500)),
                ('image', models.CharField(max_length=500)),
                ('keywords', models.CharField(max_length=500)),
                ('privacy', models.IntegerField(default=0)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.User')),
            ],
            options={
                'db_table': 'bookmarks',
            },
        ),
    ]
